### PR TITLE
Update to latest release candidate docker container

### PR DESCRIPTION
**Pull request by susannasiebert**

### CODE REVIEW

**Review by tmooney — APPROVED** [review]
+1 🖌️

**Review by tmooney — APPROVED** [review]
+1 🦗

**Review by tmooney — APPROVED** [review]
+1 🥽

**Review by tmooney — APPROVED** [review]
+1 🧩

**Comment by malachig** [comment]
I will test this PR with some full run and report back

**Comment by malachig** [comment]
Should have said that I have already test it by running `pvacseq run` stand-alone but also want to check in the pipeline context and look at more results.

**Pull request merged**
