### PR TITLE
increase space request to ensure bam can be created from cram

### PR DESCRIPTION
**Pull request by malachig**
See issue for details of error encountered that this intends to resolve:

https://github.com/wustl-oncology/analysis-wdls/issues/90

### CODE REVIEW

**Comment by tmooney** [comment]
Is 2x going to be enough?  That'd leave room for another copy of the CRAM, but as you note the BAM will be larger than that.

**Comment by malachig** [comment]
Yeah it was enough for one test dataset but not for another. But 3x worked on a very large test BAM.

**Review by tmooney — APPROVED** [review]
+1, 3x (CRAM + reference) + 10 seems as good a guess as any 🙂

**Comment by malachig** [comment]
I have now tested this on five different real datasets and its seems to be working.

**Pull request merged**
